export const DEMO_RUTINAS = [
  {
    id: "demo-upper-lower-4",
    demo: true,
    nombre: "Upper Lower 4 dias",
    descripcion: "Base de hipertrofia con volumen moderado y progresion simple.",
    objetivo: "hipertrofia",
    nivel: "intermedio",
    diasPorSemana: 4,
    duracionSemanasDefault: 6,
    visibilidad: "demo",
    ownerType: "sistema",
    tags: ["upper lower", "hipertrofia"],
    estado: "activa",
    dias: [
      {
        nombre: "Upper A",
        orden: 1,
        foco: "pecho, espalda, hombro",
        ejercicios: [
          ex("Press banca", "pecho", 4, "6-8", "2", 150),
          ex("Remo con barra", "espalda", 4, "8-10", "2", 120),
          ex("Press militar", "hombro", 3, "8-10", "2-3", 120),
          ex("Jalon al pecho", "espalda", 3, "10-12", "2", 90),
        ],
      },
      {
        nombre: "Lower A",
        orden: 2,
        foco: "pierna completa",
        ejercicios: [
          ex("Sentadilla", "cuadriceps", 4, "6-8", "2", 180),
          ex("Peso muerto rumano", "isquios", 3, "8-10", "2", 150),
          ex("Prensa", "cuadriceps", 3, "10-12", "1-2", 120),
          ex("Gemelos parado", "gemelos", 4, "12-15", "2", 75),
        ],
      },
      {
        nombre: "Upper B",
        orden: 3,
        foco: "espalda, pecho, brazos",
        ejercicios: [
          ex("Dominadas asistidas", "espalda", 4, "6-10", "2", 150),
          ex("Press inclinado mancuernas", "pecho", 3, "8-10", "2", 120),
          ex("Elevaciones laterales", "hombro", 4, "12-15", "1-2", 60),
          ex("Curl biceps", "biceps", 3, "10-12", "2", 60),
        ],
      },
      {
        nombre: "Lower B",
        orden: 4,
        foco: "gluteo e isquios",
        ejercicios: [
          ex("Hip thrust", "gluteos", 4, "8-10", "2", 150),
          ex("Bulgara", "cuadriceps", 3, "8-10", "2", 120),
          ex("Curl femoral", "isquios", 3, "10-12", "2", 90),
          ex("Plancha", "core", 3, "40-60s", "2", 60),
        ],
      },
    ],
  },
  {
    id: "demo-full-body-3",
    demo: true,
    nombre: "Full Body 3 dias",
    descripcion: "Rutina simple para construir tecnica y consistencia.",
    objetivo: "salud",
    nivel: "principiante",
    diasPorSemana: 3,
    duracionSemanasDefault: 4,
    visibilidad: "demo",
    ownerType: "sistema",
    tags: ["full body", "principiante"],
    estado: "activa",
    dias: [
      {
        nombre: "Dia A",
        orden: 1,
        foco: "base general",
        ejercicios: [
          ex("Sentadilla goblet", "cuadriceps", 3, "10-12", "3", 90),
          ex("Press pecho maquina", "pecho", 3, "10-12", "3", 90),
          ex("Remo sentado", "espalda", 3, "10-12", "3", 90),
        ],
      },
      {
        nombre: "Dia B",
        orden: 2,
        foco: "bisagra y empuje",
        ejercicios: [
          ex("Peso muerto rumano mancuernas", "isquios", 3, "10", "3", 90),
          ex("Press hombro sentado", "hombro", 3, "10-12", "3", 90),
          ex("Jalon al pecho", "espalda", 3, "10-12", "3", 90),
        ],
      },
      {
        nombre: "Dia C",
        orden: 3,
        foco: "pierna y core",
        ejercicios: [
          ex("Prensa", "cuadriceps", 3, "12", "2-3", 90),
          ex("Flexiones inclinadas", "pecho", 3, "8-12", "2-3", 75),
          ex("Plancha lateral", "core", 3, "30-45s", "2", 45),
        ],
      },
    ],
  },
  {
    id: "demo-ppl-5",
    demo: true,
    nombre: "Push Pull Legs 5 dias",
    descripcion: "Distribucion intermedia para acumular volumen sin saturar sesiones.",
    objetivo: "hipertrofia",
    nivel: "intermedio",
    diasPorSemana: 5,
    duracionSemanasDefault: 8,
    visibilidad: "demo",
    ownerType: "sistema",
    tags: ["ppl", "volumen"],
    estado: "activa",
    dias: [
      { nombre: "Push", orden: 1, foco: "pecho/hombro/triceps", ejercicios: [ex("Press banca", "pecho", 4, "6-8", "2", 150), ex("Press militar", "hombro", 3, "8", "2", 120), ex("Fondos", "triceps", 3, "8-10", "2", 90)] },
      { nombre: "Pull", orden: 2, foco: "espalda/biceps", ejercicios: [ex("Dominadas", "espalda", 4, "6-10", "2", 150), ex("Remo pecho apoyado", "espalda", 3, "8-10", "2", 120), ex("Curl inclinado", "biceps", 3, "10-12", "2", 60)] },
      { nombre: "Legs", orden: 3, foco: "pierna completa", ejercicios: [ex("Sentadilla", "cuadriceps", 4, "5-8", "2", 180), ex("Rumano", "isquios", 3, "8-10", "2", 150), ex("Extension cuadriceps", "cuadriceps", 3, "12-15", "1-2", 75)] },
      { nombre: "Upper pump", orden: 4, foco: "torso accesorio", ejercicios: [ex("Press inclinado", "pecho", 3, "10", "2", 120), ex("Jalon neutro", "espalda", 3, "10-12", "2", 90), ex("Laterales", "hombro", 4, "15", "1-2", 45)] },
      { nombre: "Lower pump", orden: 5, foco: "gluteo/isquios", ejercicios: [ex("Hip thrust", "gluteos", 4, "8-10", "2", 150), ex("Curl femoral", "isquios", 3, "12", "2", 75), ex("Gemelos", "gemelos", 4, "15", "2", 60)] },
    ],
  },
  {
    id: "demo-gluteo-pierna-4",
    demo: true,
    nombre: "Gluteos/Pierna 4 dias",
    descripcion: "Especializacion lower body con torso de mantenimiento.",
    objetivo: "hipertrofia",
    nivel: "intermedio",
    diasPorSemana: 4,
    duracionSemanasDefault: 6,
    visibilidad: "demo",
    ownerType: "sistema",
    tags: ["gluteos", "pierna"],
    estado: "activa",
    dias: [
      { nombre: "Gluteo pesado", orden: 1, foco: "gluteos", ejercicios: [ex("Hip thrust", "gluteos", 5, "5-8", "2", 180), ex("Bulgara", "gluteos", 3, "8-10", "2", 120), ex("Abduccion maquina", "gluteos", 4, "12-15", "1-2", 60)] },
      { nombre: "Torso", orden: 2, foco: "mantenimiento", ejercicios: [ex("Press maquina", "pecho", 3, "8-10", "2", 90), ex("Remo sentado", "espalda", 3, "8-10", "2", 90), ex("Laterales", "hombro", 3, "12-15", "2", 45)] },
      { nombre: "Cuadriceps", orden: 3, foco: "cuadriceps", ejercicios: [ex("Sentadilla frontal", "cuadriceps", 4, "6-8", "2", 150), ex("Prensa pies bajos", "cuadriceps", 4, "10", "2", 120), ex("Extension cuadriceps", "cuadriceps", 3, "12-15", "1-2", 75)] },
      { nombre: "Posterior", orden: 4, foco: "isquios/gluteos", ejercicios: [ex("Peso muerto rumano", "isquios", 4, "6-8", "2", 150), ex("Curl femoral", "isquios", 4, "10-12", "2", 75), ex("Patada polea", "gluteos", 3, "12-15", "2", 60)] },
    ],
  },
  {
    id: "demo-fuerza-basica-3",
    demo: true,
    nombre: "Fuerza Basica 3 dias",
    descripcion: "Practica de patrones principales con esfuerzo controlado.",
    objetivo: "fuerza",
    nivel: "principiante",
    diasPorSemana: 3,
    duracionSemanasDefault: 6,
    visibilidad: "demo",
    ownerType: "sistema",
    tags: ["fuerza", "basicos"],
    estado: "activa",
    dias: [
      { nombre: "Dia 1", orden: 1, foco: "sentadilla + banca", ejercicios: [ex("Sentadilla", "cuadriceps", 3, "5", "3", 180), ex("Press banca", "pecho", 3, "5", "3", 150), ex("Remo barra", "espalda", 3, "8", "2", 120)] },
      { nombre: "Dia 2", orden: 2, foco: "peso muerto + press", ejercicios: [ex("Peso muerto", "espalda", 3, "3-5", "3", 210), ex("Press militar", "hombro", 3, "5", "3", 150), ex("Jalon al pecho", "espalda", 3, "8", "2", 90)] },
      { nombre: "Dia 3", orden: 3, foco: "variantes", ejercicios: [ex("Sentadilla pausa", "cuadriceps", 3, "5", "3", 180), ex("Press banca agarre cerrado", "pecho", 3, "6", "3", 150), ex("Rumano", "isquios", 3, "8", "2", 120)] },
    ],
  },
];

function ex(nombre, grupo, series, reps, rir, descansoSeg) {
  return {
    ejercicioId: null,
    nombreSnapshot: nombre,
    grupoMuscularSnapshot: grupo,
    series,
    reps,
    rir,
    descansoSeg,
    tempo: "",
    notas: "",
  };
}
